#!/usr/bin/env python

print "Day1: 14 Nov, 2013"

print "Since it's the first day, I will not target for any complex problem, but from today, I will pick up a suitable problem the day before, then try to work it out on the actually day and commit. This is how I drive myself to improve and to try the habbit thing"
